SELECT NOW(), CURDATE(), CURTIME();
SELECT YEAR(NOW());
SELECT MONTH(NOW());
SELECT DAY(NOW());
SELECT HOUR(NOW());
SELECT MINUTE(NOW());
SELECT DAYNAME(NOW());
SELECT MONTHNAME(NOW());
SELECT EXTRACT(DAY FROM NOW());
SELECT EXTRACT(YEAR FROM NOW());

SELECT * 
FROM orders
WHERE order_date >= '2019-01-01';

SELECT * 
FROM orders
WHERE YEAR(order_date) = YEAR(NOW());